inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
Lint/AssignmentInCondition:
  Exclude:
  - 'app/channels/application_cable/connection.rb'
Lint/UselessAssignment:
  Exclude:
  - 'app/models/enrollment.rb'
  - 'app/workers/report_worker.rb'
  - 'lib/tasks/import.rake'
Layout/SpaceAfterComma:
  Enabled: false
Rails:
  Enabled: true
