AllCops:
  TargetRubyVersion: 2.6.2
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
Rails:
  Enabled: true
# Enable for upgrade to Ruby 3.0
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Lint/AssignmentInCondition:
  Exclude:
    - 'app/channels/application_cable/connection.rb'
Style/HashSyntax:
  Exclude:
    - 'lib/tasks/*'
Layout/SpaceAfterComma:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Max: 995
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Exclude:
    - 'lib/tasks/import_management.rake'
    - 'test/helpers/reports_helper_test.rb'
Lint/UselessAssignment:
  Exclude:
    - 'app/models/enrollment.rb'
    - 'app/workers/report_worker.rb'
    - 'lib/tasks/import.rake'
Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*'
    - 'app/models/section.rb'
Metrics/BlockNesting:
  Exclude:
    - 'app/models/section.rb'
Metrics/ClassLength:
  Exclude:
    - 'app/models/section.rb'
    - 'test/models/section_test.rb'
    - 'test/controllers/users_controller_test.rb'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/sections_controller.rb'
    - 'app/models/section.rb'
Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/sections_controller.rb'
    - 'app/models/section.rb'
Naming/PredicateName:
  Exclude:
    - 'app/models/user.rb'
Performance/RedundantMatch:
  Exclude:
    - 'app/controllers/application_controller.rb'
Performance/RegexpMatch:
  Exclude:
    - 'app/controllers/application_controller.rb'
Rails/Blank:
  Exclude:
    - 'app/workers/digest_worker.rb'
Rails/Date:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'lib/tasks/weekly_reports.rake'
Rails/FilePath:
  Exclude:
    - 'lib/tasks/import.rake'
Rails/InverseOf:
  Exclude:
    - 'app/models/section.rb'
    - 'app/models/user.rb'
Rails/Output:
  Exclude:
    - 'app/controllers/sections_controller.rb'
    - 'app/models/section.rb'
    - 'app/workers/digest_worker.rb'
    - 'app/workers/import_worker.rb'
    - 'app/workers/report_worker.rb'
Rails/OutputSafety:
  Exclude:
    - 'app/controllers/comments_controller.rb'
    - 'app/helpers/reports_helper.rb'
    - 'app/helpers/sections_helper.rb'
    - 'app/workers/digest_worker.rb'
    - 'app/workers/report_worker.rb'
Rails/Presence:
  Exclude:
    - 'app/workers/digest_worker.rb'
Rails/Present:
  Exclude:
    - 'app/controllers/sections_controller.rb'
Rails/SkipsModelValidations:
  Exclude:
    - 'app/controllers/sections_controller.rb'
    -  'app/models/section.rb'
    - 'app/models/user.rb'
    - 'test/models/section_test.rb'
Rails/TimeZone:
  Exclude:
    - 'app/controllers/sections_controller.rb'
    - 'app/models/section.rb'
    - 'app/models/user.rb'
    - 'test/models/section_test.rb'
Style/ConditionalAssignment:
  Exclude:
    - 'app/controllers/application_controller.rb'
Style/GuardClause:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/comments_controller.rb'
    - 'app/controllers/sections_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/helpers/sections_helper.rb'
    - 'app/workers/digest_worker.rb'
    - 'app/workers/new_comment_worker.rb'
Style/MethodCallWithoutArgsParentheses:
  Exclude:
    - 'app/controllers/sections_controller.rb'
    - 'app/models/section.rb'
    - 'app/models/user.rb'
    - 'lib/tasks/daily_digests.rake'
    - 'lib/tasks/weekly_reports.rake'
    - 'test/models/section_test.rb'
Style/NestedTernaryOperator:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/models/section.rb'
Style/Next:
  Exclude:
    - 'app/workers/digest_worker.rb'
    - 'app/workers/report_worker.rb'
Style/Next:
  Exclude:
    - 'app/workers/digest_worker.rb'
    - 'app/workers/report_worker.rb'
Style/PercentLiteralDelimiters:
  Exclude:
    - 'app/uploaders/feed_uploader.rb'
Style/RedundantReturn:
  Exclude:
    - 'app/controllers/comments_controller.rb'
    - 'app/controllers/sections_controller.rb'
    - 'app/controllers/users_controller.rb'
Style/RedundantSelf:
  Exclude:
    - 'app/models/section.rb'
    - 'app/models/user.rb'
Style/SafeNavigation:
  Exclude:
    - 'app/models/user.rb'
Style/NilComparison:
  Exclude:
    - 'app/controllers/application_controller.rb'
Style/UnlessElse:
  Exclude:
    - 'app/controllers/sections_controller.rb'
Style/TernaryParentheses:
  Exclude:
    - 'app/models/section.rb'
Style/NumericLiterals:
  Exclude:
    - 'test/models/section_test.rb'
