inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
Rails:
  Enabled: true
Lint/AssignmentInCondition:
  Exclude:
  - 'app/channels/application_cable/connection.rb'
Lint/UselessAssignment:
  Exclude:
  - 'app/models/enrollment.rb'
  - 'app/workers/report_worker.rb'
  - 'lib/tasks/import.rake'
Layout/SpaceAfterComma:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
  - 'lib/tasks/*'
  - 'app/models/section.rb'
Metrics/BlockNesting:
  Exclude:
  - 'app/models/section.rb'
Metrics/ClassLength:
  Exclude:
  - 'app/models/section.rb'
  - 'test/controllers/users_controller_test.rb'
Metrics/CyclomaticComplexity:
  Exclude:
  - 'app/controllers/sections_controller.rb'
  - 'app/models/section.rb'
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Exclude:
  - 'app/controllers/sections_controller.rb'
  - 'app/models/section.rb'
Naming/PredicateName:
  Exclude:
  - 'app/models/user.rb'
Metrics/LineLength:
  Enabled: false
