require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.0.3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/SpaceAfterComma:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/LineLength:
  Max: 995

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/comments_controller.rb'
    - 'app/controllers/sections_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/helpers/sections_helper.rb'
    - 'app/models/section.rb'
    - 'app/models/user.rb'
    - 'app/workers/digest_worker.rb'
    - 'app/workers/report_worker.rb'
Lint/AssignmentInCondition:
  Exclude:
    - 'app/channels/application_cable/connection.rb'
Style/HashSyntax:
  Exclude:
    - 'lib/tasks/*'
Metrics/AbcSize:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/comments_controller.rb'
    - 'app/controllers/reports_controller.rb'
    - 'app/controllers/sections_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/models/section.rb'
    - 'app/workers/digest_worker.rb'
    - 'app/workers/report_worker.rb'
    - 'lib/delivery_windows.rb'
    - 'lib/tasks/fake_a_history.rake'
Lint/UnusedMethodArgument:
  Exclude:
    - 'app/uploaders/feed_uploader.rb'
Lint/RedundantStringCoercion:
  Exclude:
    - 'lib/tasks/import.rake'
Lint/UselessAssignment:
  Exclude:
    - 'app/models/enrollment.rb'
    - 'app/workers/report_worker.rb'
    - 'lib/tasks/import.rake'
Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*'
    - 'app/models/section.rb'
Metrics/BlockNesting:
  Exclude:
    - 'app/models/section.rb'
    - 'lib/tasks/import.rake'
Metrics/ClassLength:
  Exclude:
    - 'app/models/section.rb'
    - 'test/models/section_test.rb'
    - 'test/controllers/comments_controller_test.rb'
    - 'test/controllers/users_controller_test.rb'
    - 'test/system/sections_test.rb'
    - 'test/integration/import_reporting_emails_test.rb'
    - 'test/integration/worker_reporting_emails_test.rb'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/sections_controller.rb'
    - 'app/models/section.rb'
Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/sections_controller.rb'
    - 'app/models/section.rb'
Naming/PredicateName:
  Exclude:
    - 'app/models/user.rb'
Rails/Blank:
  Exclude:
    - 'app/workers/digest_worker.rb'
Rails/Date:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'lib/tasks/weekly_reports.rake'
Rails/FilePath:
  Exclude:
    - 'lib/tasks/import.rake'
Rails/InverseOf:
  Exclude:
    - 'app/models/section.rb'
    - 'app/models/user.rb'
Rails/Output:
  Exclude:
    - 'app/controllers/sections_controller.rb'
    - 'app/models/section.rb'
    - 'app/workers/digest_worker.rb'
    - 'app/workers/import_worker.rb'
    - 'app/workers/report_worker.rb'
Rails/OutputSafety:
  Exclude:
    - 'app/controllers/comments_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/reports_helper.rb'
    - 'app/helpers/sections_helper.rb'
    - 'app/models/section.rb'
    - 'app/workers/digest_worker.rb'
    - 'app/workers/report_worker.rb'
    - 'lib/tasks/scheduler.rake'
    - 'lib/tasks/backup_db.rake'
    - 'lib/tasks/import.rake'
    - 'lib/tasks/user_reset.rake'
Rails/Presence:
  Exclude:
    - 'app/workers/digest_worker.rb'
Rails/Present:
  Exclude:
    - 'app/controllers/sections_controller.rb'
Rails/SkipsModelValidations:
  Exclude:
    - 'app/controllers/sections_controller.rb'
    -  'app/models/section.rb'
    - 'app/models/user.rb'
    - 'test/models/section_test.rb'
Rails/TimeZone:
  Exclude:
    - 'app/controllers/sections_controller.rb'
    - 'app/models/section.rb'
    - 'app/models/user.rb'
    - 'test/models/section_test.rb'
Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/reports_helper.rb'
Rails/ContentTag:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/user.rb'
Rails/WhereNot:
  Exclude:
    - 'app/models/section.rb'
Rails/WhereEquals:
  Exclude:
    - 'app/models/section.rb'
    - 'app/models/comment.rb'
Security/Open:
  Exclude:
    - 'app/models/section.rb'
Style/NumericLiterals:
  Exclude:
    - 'test/controllers/settings_controller_test.rb'
    - 'test/models/section_test.rb'
    - 'test/models/setting_test.rb'
    - 'test/system/sections_test.rb'
    - 'test/test_helper.rb'
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'
Style/EmptyMethod:
  Exclude:
    - 'app/controllers/comments_controller.rb'
    - 'app/controllers/settings_controller.rb'
    - 'app/controllers/users_controller.rb'
Style/SymbolArray:
  Exclude:
    - 'Gemfile'
    - 'app/controllers/comments_controller.rb'
    - 'app/controllers/sections_controller.rb'
    - 'app/controllers/users_controller.rb'
Style/SymbolProc:
  Exclude:
    - 'app/models/section.rb'
    - 'app/controllers/reports_controller.rb'
    - 'lib/tasks/scheduler.rake'
Style/ZeroLengthPredicate:
  Exclude:
    - 'app/models/section.rb'
Style/NumericPredicate:
  Exclude:
    - 'app/helpers/sections_helper.rb'
    - 'app/models/section.rb'
    - 'lib/tasks/import.rake'
    - 'lib/tasks/user_reset.rake'
Style/IfUnlessModifier:
  Exclude:
    - 'lib/tasks/weekly_reports.rake'
    - 'lib/tasks/daily_digests.rake'
    - 'app/workers/digest_worker.rb'
    - 'app/models/section.rb'
    - 'app/helpers/sections_helper.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/controllers/sections_controller.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/channels/department_channel.rb'
Style/StringLiteralsInInterpolation:
  Exclude:
    - 'lib/tasks/import_management.rake'
    - 'test/helpers/reports_helper_test.rb'
Style/RedundantBegin:
  Exclude:
    - 'app/models/setting.rb'
Style/MissingRespondToMissing:
  Exclude:
    - 'app/models/setting.rb'
Style/ConditionalAssignment:
  Exclude:
    - 'app/controllers/application_controller.rb'
Style/GuardClause:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/comments_controller.rb'
    - 'app/controllers/sections_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/helpers/sections_helper.rb'
    - 'app/workers/digest_worker.rb'
    - 'app/workers/new_comment_worker.rb'
Style/MethodCallWithoutArgsParentheses:
  Exclude:
    - 'app/controllers/sections_controller.rb'
    - 'app/models/section.rb'
    - 'app/models/user.rb'
    - 'lib/tasks/daily_digests.rake'
    - 'lib/tasks/weekly_reports.rake'
    - 'test/models/section_test.rb'
Style/NestedTernaryOperator:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/models/section.rb'
Style/Next:
  Exclude:
    - 'app/workers/digest_worker.rb'
    - 'app/workers/report_worker.rb'
    - 'lib/tasks/import.rake'
    - 'lib/tasks/user_reset.rake'
Style/PercentLiteralDelimiters:
  Exclude:
    - 'app/uploaders/feed_uploader.rb'
Style/RedundantReturn:
  Exclude:
    - 'app/controllers/comments_controller.rb'
    - 'app/controllers/sections_controller.rb'
    - 'app/controllers/users_controller.rb'
Style/RedundantSelf:
  Exclude:
    - 'app/models/section.rb'
    - 'app/models/user.rb'
    - 'app/uploaders/feed_uploader.rb'
Style/SafeNavigation:
  Exclude:
    - 'app/models/user.rb'
Style/NilComparison:
  Exclude:
    - 'app/controllers/application_controller.rb'
Style/UnlessElse:
  Exclude:
    - 'app/controllers/sections_controller.rb'
Style/TernaryParentheses:
  Exclude:
    - 'app/models/section.rb'
Style/SoleNestedConditional:
  Exclude:
    - 'lib/tasks/weekly_reports.rake'
    - 'lib/tasks/daily_digests.rake'
    - 'app/models/section.rb'
Style/CombinableLoops:
  Exclude:
    - 'lib/tasks/import.rake'
Style/RedundantAssignment:
  Exclude:
    - 'lib/tasks/fake_a_history.rake'
Style/StringConcatenation:
  Exclude:
    - 'app/workers/digest_worker.rb'
    - 'app/helpers/sections_helper.rb'
    - 'app/controllers/comments_controller.rb'
Style/HashLikeCase:
  Exclude:
    - 'app/helpers/sections_helper.rb'
Style/NegatedIfElseCondition:
  Exclude:
    - 'app/helpers/application_helper.rb'
Style/CaseLikeIf:
  Exclude:
    - 'app/controllers/sections_controller.rb'
Style/HashConversion:
  Exclude:
    - 'app/models/section.rb'