require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
Style/StringLiterals:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Max: 995
Style/NumericLiterals:
  Enabled: false
