development: &development
  adapter: redis
  url: redis://localhost:6379

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:b717514d3e646dd310c3dd1232af7c82@tarpon.redistogo.com:11467/
