name: brakeman

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'bin/*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'bin/*'

jobs:
  brakeman:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Brakeman
        run: bundle exec brakeman