name: test_suite

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'bin/*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'bin/*'

jobs:
  test_suite:

    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12.3
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev
      - name: Build App
        env:
          POSTGRES_HOST: localhost
          DATABASE_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PORT: 5432
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load
      - name: Run test suite
        env:
          POSTGRES_HOST: localhost
          DATABASE_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PORT: 5432
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
        run: |
          bundle exec rake assets:precompile
          bin/rails test:all
          bundle exec rake assets:clobber